### ISSUE TITLE
[Question] Exporting this library, findDomNode warning, and Transition.enter errors

### ISSUE THREAD

**Issue by lsbyerley** [jossmac/react-toast-notifications#154] opened 2021-03-04 13:44 UTC
I realize this is somewhat of a shot in the dark but I am just hoping someone could provide a clue as to how to solve the problem I am having. I am including this library in another library as the default toaster notification system. When attempting to use the Toaster in another project from this external library and calling `addToast()` I get this runtime error:

`Uncaught Error: Unable to find node on an unmounted component.
    at findHostInstanceWithWarning (index.js:87875)
    at Object.findDOMNode (index.js:88394)
    at Transition.performEnter (index.js:98118)
    at Transition.updateStatus (index.js:98101)
    at Transition.componentDidMount (index.js:98045)
    at commitLifeCycles (react-dom.development.js:20663)
    at commitLayoutEffects (react-dom.development.js:23426)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at HTMLUnknownElement.nrWrapper (newrelic-core.js:2)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)`
 
`The above error occurred in the <Transition> component:
    at Transition ...
    at TransitionGroup ..
    at div ...`

Now, I have tried to replicate this setup in a codesandbox. While I can't exactly duplicate the runtime error, i do get a warning in the console about `findDomNode` when calling `addToast()`. The way I've setup the Toaster component in the `external-lib` folder in codesandbox is how I have it in my external library. Does anyone see anything wrong with the implementation?

https://codesandbox.io/s/loving-kepler-5ixey?file=/src/App.js

screenshot of warning in codesandbox:
![Screen Shot 2021-03-04 at 8 32 36 AM](https://user-images.githubusercontent.com/3066258/109972849-be6abd80-7cc5-11eb-9383-2546e6717557.png)

EDIT: just for some more context on this.. the error is pointing to these lines in ToastContainer and ToastProvider
![Screen Shot 2021-03-04 at 2 28 25 PM](https://user-images.githubusercontent.com/3066258/110019001-ee31b980-7cf5-11eb-8ee3-1af0447d2c4c.png)
![Screen Shot 2021-03-04 at 2 27 36 PM](https://user-images.githubusercontent.com/3066258/110019006-eeca5000-7cf5-11eb-80a2-56bdf4b06223.png)

**Comment by jossmac** [comment] 2021-03-04 19:34
Thank you for the detailed bug report!

This is a duplicate of #82

**Closed by jossmac** 2021-03-04 19:34 UTC

**Comment by lsbyerley** [comment] 2021-03-04 19:39
@jossmac i was actually hoping to get some insight on why I am having the other error, not the findDomNode warning that has already been mentioned.

**Comment by jossmac** [comment] 2021-03-04 19:44
> While I can't exactly duplicate the runtime error,

Sorry @lsbyerley, it's hard for me to say without a repro

**Comment by jossmac** [comment] 2021-03-04 21:08
@lsbyerley ping me if you put together a repro, and i'll reopen.
